spring.application.name=bombtracker-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/bombtracker
spring.datasource.username=${DB_USER}
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false